### ISSUE TITLE
Add jmh benchmarks.

### ISSUE THREAD

**Issue by johnynek** [johnynek/inliner#4]
It's hard to imagine these can slow things down, but you never know the jvm's jit.

We should be benchmarking.

**Comment by jcdavis** [comment]
Also curious - I suspect the Option functions will be only marginally faster if at all faster than the default, the JVM  generally does a very good job of cleaning those up (unless inlining the lambda fails for whatever reason). More room for improvement in the collections.

**Comment by johnynek** [comment]
Working on this now.

For `inlineTry` vs Try on something that throws half the time:

```
[info] Benchmark                      Mode  Cnt    Score   Error  Units
[info] TryBenchmarks.createInlineTry  avgt   20   67.086 ± 2.004  us/op
[info] TryBenchmarks.createTry        avgt   20  128.886 ± 1.378  us/op
```
